`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Unified Sorting Visualizer Top Module
// Integrates Bubble Sort, Merge Sort, Insertion Sort, and Selection Sort Visualizations
//
// Switch Configuration:
//   - SW15: Merge Sort Demo
//   - SW15 + SW10: Merge Sort Tutorial
//   - SW14: Insertion Sort Demo
//   - SW14 + SW10: Insertion Sort Tutorial
//   - SW13: Selection Sort Demo
//   - SW13 + SW10: Selection Sort Tutorial
//   - SW12: Bubble Sort Demo
//   - SW12 + SW10: Bubble Sort Tutorial
//
// Hardware:
//   - Basys 3 FPGA Board
//   - OLED Display (PMOD connector JC)
//   - 100 MHz system clock
//////////////////////////////////////////////////////////////////////////////////

module sorting_visualizer_top(
    input wire clk,              // 100 MHz clock
    input wire btnC,             // Center button - Reset
    input wire btnU,             // Up button - Start/Run/Navigate
    input wire btnL,             // Left button - Navigate
    input wire btnR,             // Right button - Navigate
    input wire btnD,             // Down button - Pause/Resume/Navigate
    input wire [15:0] sw,        // Switches
    output wire [15:0] led,      // LEDs
    output wire [6:0] seg,       // 7-segment display segments
    output wire [3:0] an,        // 7-segment display anodes
    output wire dp,              // Decimal point
    output wire [7:0] JC         // OLED PMOD connector
);

    //==========================================================================
    // Algorithm Selection and Mode Control
    //==========================================================================
    // Check for invalid combination (more than one algorithm switch ON)
    wire invalid_combination = (sw[15] && sw[14]) || (sw[15] && sw[13]) || (sw[15] && sw[12]) ||
                               (sw[14] && sw[13]) || (sw[14] && sw[12]) || (sw[13] && sw[12]);

    // Only activate if no conflict
    wire merge_sort_active = sw[15] && !sw[14] && !sw[13] && !sw[12];     // SW15 ON, others OFF
    wire insertion_sort_active = sw[14] && !sw[15] && !sw[13] && !sw[12]; // SW14 ON, others OFF
    wire selection_sort_active = sw[13] && !sw[15] && !sw[14] && !sw[12]; // SW13 ON, others OFF
    wire bubble_sort_active = sw[12] && !sw[15] && !sw[14] && !sw[13];    // SW12 ON, others OFF

    // Tutorial mode flags
    wire merge_tutorial_mode = merge_sort_active && sw[10];        // SW15 + SW10
    wire insertion_tutorial_mode = insertion_sort_active && sw[10]; // SW14 + SW10
    // Note: selection_tutorial_mode is generated by selection_sort_controller module
    wire bubble_tutorial_mode = bubble_sort_active && sw[10];      // SW12 + SW10

    // Educational mode (demo) flags
    wire merge_demo_mode = merge_sort_active && !sw[10];           // SW15 only
    wire insertion_demo_mode = insertion_sort_active && !sw[10];   // SW14 only
    // Note: selection_demo_mode is generated by selection_sort_controller module
    wire bubble_demo_mode = bubble_sort_active && !sw[10];         // SW12 only

    // Reset signals for algorithm switching
    // Reset merge sort when other algorithms become active or invalid combination
    wire reset_merge_sort = insertion_sort_active || selection_sort_active || bubble_sort_active || invalid_combination;
    // Reset insertion sort when other algorithms become active or invalid combination
    wire reset_insertion_sort = merge_sort_active || selection_sort_active || bubble_sort_active || invalid_combination;
    // Reset selection sort when other algorithms become active or invalid combination
    wire reset_selection_sort = merge_sort_active || insertion_sort_active || bubble_sort_active || invalid_combination;
    // Reset bubble sort when other algorithms become active or invalid combination
    wire reset_bubble_sort = merge_sort_active || insertion_sort_active || selection_sort_active || invalid_combination;

    //==========================================================================
    // Clock Generation
    //==========================================================================
    wire clk_6p25MHz;
    wire clk_1hz_pulse;
    reg [15:0] clk_counter_6p25MHz = 0;
    reg [20:0] clk_counter_movement = 0;
    reg clk_6p25MHz_reg = 0;
    reg clk_movement = 0;

    // 6.25 MHz clock for OLED (100MHz / 8 = 12.5MHz, toggle = 6.25MHz)
    always @(posedge clk) begin
        clk_counter_6p25MHz <= clk_counter_6p25MHz + 1;
        if (clk_counter_6p25MHz >= 16'd7) begin
            clk_counter_6p25MHz <= 0;
            clk_6p25MHz_reg <= ~clk_6p25MHz_reg;
        end
    end
    assign clk_6p25MHz = clk_6p25MHz_reg;

    // ~45Hz movement clock for animations
    always @(posedge clk) begin
        clk_counter_movement <= clk_counter_movement + 1;
        if (clk_counter_movement >= 21'd1111111) begin
            clk_counter_movement <= 0;
            clk_movement <= ~clk_movement;
        end
    end

    //==========================================================================
    // Button Synchronization and Edge Detection
    //==========================================================================
    reg [2:0] btnU_sync = 3'b000;
    reg [2:0] btnD_sync = 3'b000;
    reg [2:0] btnC_sync = 3'b000;
    reg [2:0] btnL_sync = 3'b000;
    reg [2:0] btnR_sync = 3'b000;

    always @(posedge clk) begin
        btnU_sync <= {btnU_sync[1:0], btnU};
        btnD_sync <= {btnD_sync[1:0], btnD};
        btnC_sync <= {btnC_sync[1:0], btnC};
        btnL_sync <= {btnL_sync[1:0], btnL};
        btnR_sync <= {btnR_sync[1:0], btnR};
    end

    // Edge detection
    wire btn_start = btnU_sync[2] && !btnU_sync[1];
    wire btn_pause = btnD_sync[2] && !btnD_sync[1];
    wire btn_center = btnC_sync[2] && !btnC_sync[1];
    wire btn_left = btnL_sync[2] && !btnL_sync[1];
    wire btn_right = btnR_sync[2] && !btnR_sync[1];

    // Reset signals - combine button press with algorithm switching
    // Merge sort resets when: button pressed (not in tutorial) OR bubble sort activated
    wire btn_reset_merge = (btn_center && !merge_tutorial_mode) || reset_merge_sort;
    // Bubble sort resets when: button pressed OR merge sort activated
    wire btn_reset_bubble = btn_center || reset_bubble_sort;

    //==========================================================================
    // OLED Display Interface (Shared)
    //==========================================================================
    wire frame_begin, sending_pixels, sample_pixel;
    wire [12:0] pixel_index;
    wire [15:0] pixel_data_final;

    // OLED display reset when invalid combination or no algorithm active
    wire oled_reset = invalid_combination || (!merge_sort_active && !insertion_sort_active && !selection_sort_active && !bubble_sort_active);

    Oled_Display oled_display (
        .clk(clk_6p25MHz),
        .reset(oled_reset),
        .frame_begin(frame_begin),
        .sending_pixels(sending_pixels),
        .sample_pixel(sample_pixel),
        .pixel_index(pixel_index),
        .pixel_data(pixel_data_final),
        .cs(JC[0]),
        .sdin(JC[1]),
        .sclk(JC[3]),
        .d_cn(JC[4]),
        .resn(JC[5]),
        .vccen(JC[6]),
        .pmoden(JC[7])
    );
    assign JC[2] = 0; // Unused pin

    //==========================================================================
    // Merge Sort Visualization System
    //==========================================================================
    wire [17:0] merge_array_data_flat;
    wire [17:0] merge_answer_data_flat;
    wire [35:0] merge_array_positions_y_flat;
    wire [41:0] merge_array_positions_x_flat;
    wire [17:0] merge_array_colors_flat;
    wire [17:0] merge_answer_colors_flat;
    wire [4:0] merge_separator_visible;
    wire [14:0] merge_separator_colors_flat;
    wire [2:0] merge_cursor_pos;
    wire merge_practice_mode_active;
    wire [2:0] merge_sort_current_state;
    wire [2:0] merge_divide_step_status;
    wire [2:0] merge_merge_step_status;
    wire merge_sorting_active, merge_animation_busy, merge_sort_complete;
    wire merge_all_positions_reached;
    wire merge_pulse_state_signal;
    wire [5:0] merge_region_active_signal;
    wire [5:0] merge_hint_timer_signal;
    wire [4:0] merge_hint_separators_signal;
    wire [15:0] merge_pixel_data;

    // Merge Sort Controller
    merge_sort_controller merge_controller (
        .clk(clk),
        .clk_6p25MHz(clk_6p25MHz),
        .clk_movement(clk_movement),
        .reset(btn_reset_merge),
        .btn_start(btn_start),
        .btn_pause(btn_pause),
        .btn_left(btn_left),
        .btn_right(btn_right),
        .btn_center(btn_center),
        .demo_active(merge_sort_active),
        .educational_mode(merge_demo_mode),
        .tutorial_mode(merge_tutorial_mode),
        .line_switches(sw[4:0]),
        .array_data_flat(merge_array_data_flat),
        .answer_data_flat(merge_answer_data_flat),
        .array_positions_y_flat(merge_array_positions_y_flat),
        .array_positions_x_flat(merge_array_positions_x_flat),
        .array_colors_flat(merge_array_colors_flat),
        .answer_colors_flat(merge_answer_colors_flat),
        .separator_visible(merge_separator_visible),
        .separator_colors_flat(merge_separator_colors_flat),
        .cursor_pos_out(merge_cursor_pos),
        .practice_mode_active(merge_practice_mode_active),
        .current_state(merge_sort_current_state),
        .divide_step_out(merge_divide_step_status),
        .merge_step_out(merge_merge_step_status),
        .sorting_active(merge_sorting_active),
        .animation_busy(merge_animation_busy),
        .sort_complete(merge_sort_complete),
        .all_positions_reached(merge_all_positions_reached),
        .pulse_state_out(merge_pulse_state_signal),
        .merge_region_active_flat(merge_region_active_signal),
        .hint_timer_out(merge_hint_timer_signal),
        .hint_separators_flat(merge_hint_separators_signal)
    );

    // Merge Sort Display Engine
    merge_sort_display merge_display_engine (
        .clk_6p25MHz(clk_6p25MHz),
        .reset(btn_reset_merge),
        .pixel_index(pixel_index),
        .pixel_data(merge_pixel_data),
        .array_data_flat(merge_array_data_flat),
        .answer_data_flat(merge_answer_data_flat),
        .array_positions_y_flat(merge_array_positions_y_flat),
        .array_positions_x_flat(merge_array_positions_x_flat),
        .array_colors_flat(merge_array_colors_flat),
        .answer_colors_flat(merge_answer_colors_flat),
        .separator_visible(merge_separator_visible),
        .separator_colors_flat(merge_separator_colors_flat),
        .cursor_pos(merge_cursor_pos),
        .practice_mode_active(merge_practice_mode_active),
        .current_state(merge_sort_current_state),
        .divide_step(merge_divide_step_status),
        .merge_step(merge_merge_step_status),
        .sorting_active(merge_sorting_active),
        .demo_active(merge_sort_active),
        .pulse_state(merge_pulse_state_signal),
        .merge_region_active(merge_region_active_signal),
        .hint_timer(merge_hint_timer_signal),
        .hint_separators(merge_hint_separators_signal)
    );

    //==========================================================================
    // Bubble Sort Visualization System
    //==========================================================================
    // Bubble sort FSM signals
    wire [7:0] bubble_array0, bubble_array1, bubble_array2;
    wire [7:0] bubble_array3, bubble_array4, bubble_array5;
    wire [2:0] bubble_compare_idx1, bubble_compare_idx2;
    wire bubble_swap_flag, bubble_sorting, bubble_done;
    wire [5:0] bubble_anim_progress;
    wire [1:0] bubble_anim_phase;
    wire [15:0] bubble_pixel_data_auto, bubble_pixel_data_tutorial;
    wire [15:0] bubble_pixel_data;

    // Tutorial mode signals for bubble sort
    wire [7:0] bubble_tutorial_array0, bubble_tutorial_array1, bubble_tutorial_array2;
    wire [7:0] bubble_tutorial_array3, bubble_tutorial_array4, bubble_tutorial_array5;
    wire [2:0] bubble_tutorial_cursor_pos, bubble_tutorial_compare_pos;
    wire [4:0] bubble_tutorial_anim_frame;
    wire [6:0] bubble_tutorial_progress;
    wire bubble_tutorial_feedback_correct, bubble_tutorial_feedback_incorrect;
    wire bubble_tutorial_is_sorted;
    wire [3:0] bubble_tutorial_state;

    // Pause state for bubble sort auto mode
    reg bubble_paused;
    always @(posedge clk) begin
        if (btn_reset_bubble)
            bubble_paused <= 0;
        else if (btn_pause && !bubble_tutorial_mode)
            bubble_paused <= ~bubble_paused;
    end

    // Frame tick generator for bubble sort tutorial animations (~60 Hz)
    reg [20:0] bubble_frame_counter;
    reg bubble_frame_tick;
    always @(posedge clk) begin
        if (bubble_frame_counter >= 21'd1666666) begin
            bubble_frame_counter <= 0;
            bubble_frame_tick <= 1;
        end else begin
            bubble_frame_counter <= bubble_frame_counter + 1;
            bubble_frame_tick <= 0;
        end
    end

    // Button debouncing for bubble sort
    wire bubble_btn_l_edge, bubble_btn_r_edge, bubble_btn_u_edge;
    wire bubble_btn_d_edge, bubble_btn_c_edge;

    button_debounce_5btn bubble_btn_debouncer (
        .clk(clk),
        .reset(1'b0),
        .btnL(btnL),
        .btnR(btnR),
        .btnU(btnU),
        .btnD(btnD),
        .btnC(btnC),
        .btn_l_edge(bubble_btn_l_edge),
        .btn_r_edge(bubble_btn_r_edge),
        .btn_u_edge(bubble_btn_u_edge),
        .btn_d_edge(bubble_btn_d_edge),
        .btn_c_edge(bubble_btn_c_edge)
    );

    // Clock divider for bubble sort (1Hz pulse)
    wire bubble_clk_1hz_pulse;
    wire bubble_clk_1hz_pulse_gated;
    clock_divider bubble_clk_div (
        .clk_100mhz(clk),
        .rst(btn_reset_bubble),
        .clk_6p25mhz(),  // Not used, we use shared clk_6p25MHz
        .clk_1hz_pulse(bubble_clk_1hz_pulse)
    );
    // Gate step pulse during animation to prevent state machine from advancing during swap
    assign bubble_clk_1hz_pulse_gated = bubble_clk_1hz_pulse && !bubble_paused && !bubble_swap_flag;

    // Bubble Sort FSM (auto mode)
    bubble_sort_fsm bubble_fsm (
        .clk(clk),
        .rst(btn_reset_bubble),
        .start(bubble_btn_u_edge),
        .step_pulse(bubble_clk_1hz_pulse_gated),
        .pattern_sel(sw[1:0]),
        .array0(bubble_array0),
        .array1(bubble_array1),
        .array2(bubble_array2),
        .array3(bubble_array3),
        .array4(bubble_array4),
        .array5(bubble_array5),
        .compare_idx1(bubble_compare_idx1),
        .compare_idx2(bubble_compare_idx2),
        .swap_flag(bubble_swap_flag),
        .anim_progress(bubble_anim_progress),
        .anim_phase(bubble_anim_phase),
        .sorting(bubble_sorting),
        .done(bubble_done)
    );

    // Tutorial FSM for bubble sort
    tutorial_fsm bubble_tutorial (
        .clk(clk),
        .reset(btn_reset_bubble),
        .enable(bubble_tutorial_mode),
        .btn_l_edge(bubble_btn_l_edge),
        .btn_r_edge(bubble_btn_r_edge),
        .btn_u_edge(bubble_btn_u_edge),
        .btn_d_edge(bubble_btn_d_edge),
        .btn_c_edge(bubble_btn_c_edge),
        .frame_tick(bubble_frame_tick),
        .array0(bubble_tutorial_array0),
        .array1(bubble_tutorial_array1),
        .array2(bubble_tutorial_array2),
        .array3(bubble_tutorial_array3),
        .array4(bubble_tutorial_array4),
        .array5(bubble_tutorial_array5),
        .cursor_pos(bubble_tutorial_cursor_pos),
        .compare_pos(bubble_tutorial_compare_pos),
        .anim_frame(bubble_tutorial_anim_frame),
        .progress_percent(bubble_tutorial_progress),
        .feedback_correct(bubble_tutorial_feedback_correct),
        .feedback_incorrect(bubble_tutorial_feedback_incorrect),
        .is_sorted(bubble_tutorial_is_sorted),
        .current_state_num(bubble_tutorial_state)
    );

    // Mux between auto and tutorial mode for bubble sort
    wire [7:0] bubble_final_array0 = bubble_tutorial_mode ? bubble_tutorial_array0 : bubble_array0;
    wire [7:0] bubble_final_array1 = bubble_tutorial_mode ? bubble_tutorial_array1 : bubble_array1;
    wire [7:0] bubble_final_array2 = bubble_tutorial_mode ? bubble_tutorial_array2 : bubble_array2;
    wire [7:0] bubble_final_array3 = bubble_tutorial_mode ? bubble_tutorial_array3 : bubble_array3;
    wire [7:0] bubble_final_array4 = bubble_tutorial_mode ? bubble_tutorial_array4 : bubble_array4;
    wire [7:0] bubble_final_array5 = bubble_tutorial_mode ? bubble_tutorial_array5 : bubble_array5;
    wire [2:0] bubble_final_compare_idx1 = bubble_tutorial_mode ? bubble_tutorial_cursor_pos : bubble_compare_idx1;
    wire [2:0] bubble_final_compare_idx2 = bubble_tutorial_mode ? bubble_tutorial_compare_pos : bubble_compare_idx2;
    wire bubble_final_swap_flag = bubble_tutorial_mode ? 1'b0 : bubble_swap_flag;
    wire [5:0] bubble_final_anim_progress = bubble_tutorial_mode ? 6'b0 : bubble_anim_progress;
    wire [1:0] bubble_final_anim_phase = bubble_tutorial_mode ? 2'b0 : bubble_anim_phase;
    wire bubble_final_sorting = bubble_tutorial_mode ? (!bubble_tutorial_is_sorted) : bubble_sorting;
    wire bubble_final_done = bubble_tutorial_mode ? bubble_tutorial_is_sorted : bubble_done;

    // Pixel generators for bubble sort
    pixel_generator bubble_pix_gen_auto (
        .pixel_index(pixel_index),
        .array0(bubble_final_array0),
        .array1(bubble_final_array1),
        .array2(bubble_final_array2),
        .array3(bubble_final_array3),
        .array4(bubble_final_array4),
        .array5(bubble_final_array5),
        .compare_idx1(bubble_final_compare_idx1),
        .compare_idx2(bubble_final_compare_idx2),
        .swap_flag(bubble_final_swap_flag),
        .anim_progress(bubble_final_anim_progress),
        .anim_phase(bubble_final_anim_phase),
        .sorting(bubble_final_sorting),
        .done(bubble_final_done),
        .pixel_data(bubble_pixel_data_auto)
    );

    tutorial_pixel_generator bubble_pix_gen_tutorial (
        .pixel_index(pixel_index),
        .array0(bubble_tutorial_array0),
        .array1(bubble_tutorial_array1),
        .array2(bubble_tutorial_array2),
        .array3(bubble_tutorial_array3),
        .array4(bubble_tutorial_array4),
        .array5(bubble_tutorial_array5),
        .cursor_pos(bubble_tutorial_cursor_pos),
        .compare_pos(bubble_tutorial_compare_pos),
        .anim_frame(bubble_tutorial_anim_frame),
        .progress_percent(bubble_tutorial_progress),
        .feedback_correct(bubble_tutorial_feedback_correct),
        .feedback_incorrect(bubble_tutorial_feedback_incorrect),
        .is_sorted(bubble_tutorial_is_sorted),
        .current_state(bubble_tutorial_state),
        .pixel_data(bubble_pixel_data_tutorial)
    );

    // Multiplex bubble sort pixel data
    assign bubble_pixel_data = bubble_tutorial_mode ? bubble_pixel_data_tutorial : bubble_pixel_data_auto;

    //==========================================================================
    // Insertion Sort Visualization System
    //==========================================================================
    // Clock enable signals for insertion sort renderer
    wire insertion_ce_30hz, insertion_ce_2hz;

    Clock_Generator insertion_clk_gen(
        .clk_100mhz(clk),
        .reset(reset_insertion_sort),
        .ce_1mhz(),      // Not used
        .ce_30hz(insertion_ce_30hz),
        .ce_2hz(insertion_ce_2hz)
    );

    // Button pulses for insertion sort (reuse existing edge detection signals)
    wire insertion_btnC_pulse = btn_center && insertion_sort_active;
    wire insertion_btnL_pulse = btn_left && insertion_sort_active;
    wire insertion_btnR_pulse = btn_right && insertion_sort_active;
    wire insertion_btnU_pulse = btn_start && insertion_sort_active;
    wire insertion_btnD_pulse = btn_pause && insertion_sort_active;

    // Insertion Sort FSM signals
    wire [2:0] insertion_current_screen;
    wire insertion_sort_engine_next, insertion_sort_engine_prev, insertion_sort_engine_reset;
    wire insertion_is_sorted_flag, insertion_is_at_start_flag;
    wire insertion_tut_inc_val, insertion_tut_dec_val;
    wire insertion_tut_move_cursor_r, insertion_tut_move_cursor_l;
    wire insertion_tut_sort_compare_left, insertion_tut_sort_compare_right;
    wire insertion_tut_sort_swap, insertion_tut_sort_keep, insertion_tut_sort_reset;
    wire insertion_tut_sort_is_victory, insertion_tut_sort_is_game_over;

    // Demo mode array signals
    wire [2:0] insertion_array_0, insertion_array_1, insertion_array_2;
    wire [2:0] insertion_array_3, insertion_array_4, insertion_array_5;
    wire [2:0] insertion_red_line_pos;
    wire [2:0] insertion_compare_idx1, insertion_compare_idx2;
    wire [2:0] insertion_swap_idx1, insertion_swap_idx2;

    // Tutorial input engine signals
    wire [2:0] insertion_tut_array_0, insertion_tut_array_1, insertion_tut_array_2;
    wire [2:0] insertion_tut_array_3, insertion_tut_array_4, insertion_tut_array_5;
    wire [2:0] insertion_cursor_pos;

    // Tutorial sort engine signals
    wire [2:0] insertion_tut_sort_array_0, insertion_tut_sort_array_1, insertion_tut_sort_array_2;
    wire [2:0] insertion_tut_sort_array_3, insertion_tut_sort_array_4, insertion_tut_sort_array_5;
    wire [2:0] insertion_tut_sort_red_line_pos;
    wire [2:0] insertion_tut_sort_compare_idx1, insertion_tut_sort_compare_idx2;
    wire [2:0] insertion_tut_sort_swap_idx1, insertion_tut_sort_swap_idx2;
    wire [2:0] insertion_tut_sort_hearts_remaining;
    wire insertion_tut_sort_show_mistake;

    // Framebuffer signals for insertion sort
    wire insertion_fb_wr_en;
    wire [12:0] insertion_fb_wr_addr;
    wire [15:0] insertion_fb_wr_data;
    wire [12:0] insertion_fb_rd_addr;
    wire [15:0] insertion_fb_rd_data;

    // Main FSM for Insertion Sort
    Main_FSM insertion_main_fsm(
        .clk_100mhz(clk),
        .reset(reset_insertion_sort),
        .tutorial_mode_active(insertion_tutorial_mode),
        .btnC_pulse(insertion_btnC_pulse),
        .btnL_pulse(insertion_btnL_pulse),
        .btnR_pulse(insertion_btnR_pulse),
        .btnU_pulse(insertion_btnU_pulse),
        .btnD_pulse(insertion_btnD_pulse),
        .sort_engine_is_sorted_flag(insertion_is_sorted_flag),
        .sort_engine_is_at_start_flag(insertion_is_at_start_flag),
        .tut_sort_is_victory(insertion_tut_sort_is_victory),
        .tut_sort_is_game_over(insertion_tut_sort_is_game_over),
        .current_screen(insertion_current_screen),
        .sort_engine_next(insertion_sort_engine_next),
        .sort_engine_prev(insertion_sort_engine_prev),
        .sort_engine_reset(insertion_sort_engine_reset),
        .tut_inc_val(insertion_tut_inc_val),
        .tut_dec_val(insertion_tut_dec_val),
        .tut_move_cursor_r(insertion_tut_move_cursor_r),
        .tut_move_cursor_l(insertion_tut_move_cursor_l),
        .tut_sort_compare_left(insertion_tut_sort_compare_left),
        .tut_sort_compare_right(insertion_tut_sort_compare_right),
        .tut_sort_swap(insertion_tut_sort_swap),
        .tut_sort_keep(insertion_tut_sort_keep),
        .tut_sort_reset(insertion_tut_sort_reset)
    );

    // Sort Engine (Demo Mode)
    Sort_Engine insertion_sort_engine(
        .clk_100mhz(clk),
        .reset(reset_insertion_sort || insertion_sort_engine_reset),
        .next_step_pulse(insertion_sort_engine_next),
        .prev_step_pulse(insertion_sort_engine_prev),
        .current_array_0(insertion_array_0),
        .current_array_1(insertion_array_1),
        .current_array_2(insertion_array_2),
        .current_array_3(insertion_array_3),
        .current_array_4(insertion_array_4),
        .current_array_5(insertion_array_5),
        .red_line_pos(insertion_red_line_pos),
        .compare_idx1(insertion_compare_idx1),
        .compare_idx2(insertion_compare_idx2),
        .swap_idx1(insertion_swap_idx1),
        .swap_idx2(insertion_swap_idx2),
        .is_sorted_flag(insertion_is_sorted_flag),
        .is_at_start_flag(insertion_is_at_start_flag)
    );

    // Tutorial Input Engine
    Tutorial_Input_Engine insertion_tut_input_engine(
        .clk_100mhz(clk),
        .reset(reset_insertion_sort),
        .tutorial_mode_active(insertion_tutorial_mode),
        .inc_val_pulse(insertion_tut_inc_val),
        .dec_val_pulse(insertion_tut_dec_val),
        .move_r_pulse(insertion_tut_move_cursor_r),
        .move_l_pulse(insertion_tut_move_cursor_l),
        .tut_array_0(insertion_tut_array_0),
        .tut_array_1(insertion_tut_array_1),
        .tut_array_2(insertion_tut_array_2),
        .tut_array_3(insertion_tut_array_3),
        .tut_array_4(insertion_tut_array_4),
        .tut_array_5(insertion_tut_array_5),
        .cursor_pos(insertion_cursor_pos)
    );

    // Tutorial Sort Engine
    Tutorial_Sort_Engine insertion_tut_sort_engine(
        .clk_100mhz(clk),
        .reset(insertion_tut_sort_reset),
        .compare_left_pulse(insertion_tut_sort_compare_left),
        .compare_right_pulse(insertion_tut_sort_compare_right),
        .swap_pulse(insertion_tut_sort_swap),
        .keep_pulse(insertion_tut_sort_keep),
        .input_array_0(insertion_tut_array_0),
        .input_array_1(insertion_tut_array_1),
        .input_array_2(insertion_tut_array_2),
        .input_array_3(insertion_tut_array_3),
        .input_array_4(insertion_tut_array_4),
        .input_array_5(insertion_tut_array_5),
        .current_array_0(insertion_tut_sort_array_0),
        .current_array_1(insertion_tut_sort_array_1),
        .current_array_2(insertion_tut_sort_array_2),
        .current_array_3(insertion_tut_sort_array_3),
        .current_array_4(insertion_tut_sort_array_4),
        .current_array_5(insertion_tut_sort_array_5),
        .red_line_pos(insertion_tut_sort_red_line_pos),
        .compare_idx1(insertion_tut_sort_compare_idx1),
        .compare_idx2(insertion_tut_sort_compare_idx2),
        .swap_idx1(insertion_tut_sort_swap_idx1),
        .swap_idx2(insertion_tut_sort_swap_idx2),
        .hearts_remaining(insertion_tut_sort_hearts_remaining),
        .is_victory(insertion_tut_sort_is_victory),
        .is_game_over(insertion_tut_sort_is_game_over),
        .show_mistake(insertion_tut_sort_show_mistake)
    );

    // OLED Renderer for Insertion Sort
    Oled_Renderer insertion_renderer(
        .clk_100mhz(clk),
        .ce_30hz(insertion_ce_30hz),
        .ce_2hz(insertion_ce_2hz),
        .system_enable(insertion_sort_active),
        .current_screen(insertion_current_screen),
        .frame_begin(frame_begin),
        .sending_pixels(sending_pixels),
        .current_array_0(insertion_array_0),
        .current_array_1(insertion_array_1),
        .current_array_2(insertion_array_2),
        .current_array_3(insertion_array_3),
        .current_array_4(insertion_array_4),
        .current_array_5(insertion_array_5),
        .red_line_pos(insertion_red_line_pos),
        .compare_idx1(insertion_compare_idx1),
        .compare_idx2(insertion_compare_idx2),
        .swap_idx1(insertion_swap_idx1),
        .swap_idx2(insertion_swap_idx2),
        .is_sorted_flag(insertion_is_sorted_flag),
        .is_at_start_flag(insertion_is_at_start_flag),
        .tut_array_0(insertion_tut_array_0),
        .tut_array_1(insertion_tut_array_1),
        .tut_array_2(insertion_tut_array_2),
        .tut_array_3(insertion_tut_array_3),
        .tut_array_4(insertion_tut_array_4),
        .tut_array_5(insertion_tut_array_5),
        .cursor_pos(insertion_cursor_pos),
        .tut_sort_array_0(insertion_tut_sort_array_0),
        .tut_sort_array_1(insertion_tut_sort_array_1),
        .tut_sort_array_2(insertion_tut_sort_array_2),
        .tut_sort_array_3(insertion_tut_sort_array_3),
        .tut_sort_array_4(insertion_tut_sort_array_4),
        .tut_sort_array_5(insertion_tut_sort_array_5),
        .tut_red_line_pos(insertion_tut_sort_red_line_pos),
        .tut_compare_idx1(insertion_tut_sort_compare_idx1),
        .tut_compare_idx2(insertion_tut_sort_compare_idx2),
        .tut_swap_idx1(insertion_tut_sort_swap_idx1),
        .tut_swap_idx2(insertion_tut_sort_swap_idx2),
        .hearts_remaining(insertion_tut_sort_hearts_remaining),
        .show_mistake(insertion_tut_sort_show_mistake),
        .fb_wr_en(insertion_fb_wr_en),
        .fb_wr_addr(insertion_fb_wr_addr),
        .fb_wr_data(insertion_fb_wr_data)
    );

    // Frame Buffer for Insertion Sort
    Frame_Buffer insertion_frame_buffer(
        .clk(clk),
        .wr_en(insertion_fb_wr_en),
        .wr_addr(insertion_fb_wr_addr),
        .wr_data(insertion_fb_wr_data),
        .rd_addr(insertion_fb_rd_addr),
        .rd_data(insertion_fb_rd_data)
    );

    // Connect framebuffer read address to pixel index when insertion sort is active
    assign insertion_fb_rd_addr = pixel_index;

    //==========================================================================
    // Selection Sort Visualization System
    //==========================================================================
    // Clock dividers for selection sort
    wire selection_clk_1ms;

    clock_divider_1ms selection_clk_div_1ms(
        .clk(clk),
        .clk_1ms(selection_clk_1ms)
    );

    // Text animator for selection sort
    wire [2:0] selection_anim_offset;

    text_animator selection_text_anim(
        .clk_1ms(selection_clk_1ms),
        .reset(reset_selection_sort),
        .enable(selection_sort_active),
        .offset(selection_anim_offset)
    );

    // Selection sort controller signals
    wire [17:0] selection_array_flat;
    wire [2:0] selection_current_i;
    wire [2:0] selection_current_j;
    wire [2:0] selection_min_idx;
    wire [1:0] selection_wrong_attempt_count;
    wire selection_sorting_active;
    wire [1:0] selection_state_type;
    wire selection_sort_complete;
    wire [2:0] selection_intro_state;
    wire selection_demo_mode;
    wire selection_tutorial_mode;
    wire [3:0] selection_tutorial_state;
    wire [2:0] selection_selected_box;
    wire [17:0] selection_tutorial_array;
    wire [11:0] selection_tutorial_timer;
    wire [5:0] selection_box_confirmed;
    wire [2:0] selection_test_cursor_pos;
    wire [2:0] selection_test_unsorted_idx;
    wire selection_test_selecting_swap;
    wire [2:0] selection_user_min_selected;
    wire [7:0] selection_comparison_count;
    wire [7:0] selection_swap_count;
    wire selection_manual_step_mode;
    wire [2:0] selection_tutorial_progress;
    wire selection_show_swap_info;

    // Selection sort pixel data
    wire [15:0] selection_pixel_data;

    // Selection Sort Controller
    selection_sort_controller selection_controller(
        .clk(selection_clk_1ms),
        .reset(reset_selection_sort),
        .enable(selection_sort_active),
        .ctr_button(btnC),
        .sw10(sw[10]),
        .sw7(sw[7]),
        .btnU(btnU),
        .btnD(btnD),
        .btnL(btnL),
        .btnR(btnR),
        .array_flat(selection_array_flat),
        .current_i(selection_current_i),
        .current_j(selection_current_j),
        .min_idx(selection_min_idx),
        .wrong_attempt_count(selection_wrong_attempt_count),
        .sorting_active(selection_sorting_active),
        .state_type(selection_state_type),
        .sort_complete(selection_sort_complete),
        .intro_state(selection_intro_state),
        .demo_mode(selection_demo_mode),
        .tutorial_mode(selection_tutorial_mode),
        .tutorial_state(selection_tutorial_state),
        .selected_box(selection_selected_box),
        .tutorial_array(selection_tutorial_array),
        .tutorial_timer(selection_tutorial_timer),
        .box_confirmed(selection_box_confirmed),
        .test_cursor_pos(selection_test_cursor_pos),
        .test_unsorted_idx(selection_test_unsorted_idx),
        .test_selecting_swap(selection_test_selecting_swap),
        .user_min_selected(selection_user_min_selected),
        .comparison_count(selection_comparison_count),
        .swap_count(selection_swap_count),
        .manual_step_mode(selection_manual_step_mode),
        .tutorial_progress(selection_tutorial_progress),
        .show_swap_info(selection_show_swap_info)
    );

    // Selection Sort Display Generator
    display_generator_comb selection_display(
        .enable(selection_sort_active),
        .pixel_index(pixel_index),
        .show_swap_info(selection_show_swap_info),
        .array_flat(selection_array_flat),
        .current_i(selection_current_i),
        .current_j(selection_current_j),
        .min_idx(selection_min_idx),
        .sorting_active(selection_sorting_active),
        .state_type(selection_state_type),
        .intro_state(selection_intro_state),
        .anim_offset(selection_anim_offset),
        .sort_complete(selection_sort_complete),
        .tutorial_mode(selection_tutorial_mode),
        .tutorial_state(selection_tutorial_state),
        .selected_box(selection_selected_box),
        .tutorial_array(selection_tutorial_array),
        .tutorial_timer(selection_tutorial_timer),
        .box_confirmed(selection_box_confirmed),
        .test_cursor_pos(selection_test_cursor_pos),
        .test_unsorted_idx(selection_test_unsorted_idx),
        .test_selecting_swap(selection_test_selecting_swap),
        .wrong_attempt_count(selection_wrong_attempt_count),
        .comparison_count(selection_comparison_count),
        .swap_count(selection_swap_count),
        .user_min_selected(selection_user_min_selected),
        .tutorial_progress(selection_tutorial_progress),
        .pixel_data(selection_pixel_data)
    );

    //==========================================================================
    // Output Multiplexing
    //==========================================================================
    // OLED pixel data multiplexing
    // Insertion sort uses framebuffer, merge/bubble/selection use direct pixel generation
    assign pixel_data_final = merge_sort_active ? merge_pixel_data :
                              insertion_sort_active ? insertion_fb_rd_data :
                              selection_sort_active ? selection_pixel_data :
                              bubble_sort_active ? bubble_pixel_data :
                              16'h0000; // Black screen when no algorithm active

    // LED multiplexing
    reg [15:0] led_output;
    assign led = led_output;

    always @(*) begin
        if (invalid_combination) begin
            // Invalid combination - show warning
            led_output = 16'h0000;
            led_output[15] = sw[15];  // Show which switches are ON
            led_output[14] = sw[14];
            led_output[13] = sw[13];
            led_output[12] = sw[12];
        end else if (merge_sort_active) begin
            // Merge sort LED status
            led_output[15] = merge_sort_active;
            led_output[14] = merge_sorting_active;
            led_output[13] = merge_animation_busy;
            led_output[12] = merge_sort_complete;
            led_output[11:8] = {1'b0, merge_sort_current_state};
            led_output[7:0] = 8'h00;
        end else if (insertion_sort_active) begin
            // Insertion sort LED status
            led_output = 16'h0000;
            led_output[14] = insertion_sort_active;
            led_output[10] = insertion_tutorial_mode;
            led_output[0] = insertion_is_sorted_flag;
        end else if (selection_sort_active) begin
            // Selection sort LED status
            led_output = 16'h0000;
            led_output[13] = selection_sort_active;
            led_output[10] = selection_tutorial_mode;
            led_output[7:5] = selection_tutorial_progress;  // Show tutorial progress (0-6)
            led_output[0] = selection_sort_complete;
        end else if (bubble_sort_active) begin
            // Bubble sort LED status
            led_output = 16'h0000;
            led_output[12] = bubble_sort_active;
            led_output[0] = bubble_tutorial_mode;
        end else begin
            led_output = 16'h0000;
        end
    end

    //==========================================================================
    // Seven-Segment Display
    //==========================================================================
    reg [19:0] display_counter = 0;
    reg [1:0] digit_select = 0;

    always @(posedge clk) begin
        display_counter <= display_counter + 1;
        if (display_counter == 0) begin
            digit_select <= digit_select + 1;
        end
    end

    // Segment patterns for merge sort - displays "MErG"
    localparam SEG_M = 7'b1101010;  // "M"
    localparam SEG_E = 7'b0000110;  // "E"
    localparam SEG_R = 7'b0101111;  // "r"
    localparam SEG_G = 7'b0010000;  // "G"

    // Segment patterns for insertion sort - displays "InSt"
    localparam SEG_I = 7'b1001111;  // "I"
    localparam SEG_N_LOWER = 7'b1010100;  // "n"
    localparam SEG_S = 7'b0100100;  // "S"
    localparam SEG_T = 7'b0000111;  // "t"

    // Segment patterns for bubble sort - displays "bUbL" or "tutr"
    localparam SEG_B_LOWER = 7'b1111100;  // "b"
    localparam SEG_U_UPPER = 7'b0111110;  // "U"
    localparam SEG_L_UPPER = 7'b0111000;  // "L"
    localparam SEG_T_LOWER = 7'b1111000;  // "t"
    localparam SEG_R_LOWER = 7'b1010000;  // "r"

    // Segment patterns for selection sort - displays "SELt"
    // SEG_S, SEG_E, SEG_L_UPPER, SEG_T_LOWER already defined above

    // Segment patterns for error - displays "Err"
    localparam SEG_DASH = 7'b1000000;     // "-"
    localparam SEG_E_ERROR = ~7'b0000110; // "E" for error (inverted from normal E)

    reg [6:0] seg_pattern;
    reg [3:0] anode_pattern;

    always @(*) begin
        if (invalid_combination) begin
            // Display "Err-" for invalid combination
            case (digit_select)
                2'b00: begin anode_pattern = 4'b1110; seg_pattern = SEG_DASH; end      // Rightmost: "-"
                2'b01: begin anode_pattern = 4'b1101; seg_pattern = SEG_R_LOWER; end   // "r"
                2'b10: begin anode_pattern = 4'b1011; seg_pattern = SEG_R_LOWER; end   // "r"
                2'b11: begin anode_pattern = 4'b0111; seg_pattern = SEG_E_ERROR; end   // Leftmost: "E" (special pattern)
            endcase
        end else if (merge_sort_active) begin
            // Display "MErG" for merge sort
            case (digit_select)
                2'b00: begin anode_pattern = 4'b1110; seg_pattern = SEG_G; end     // Rightmost
                2'b01: begin anode_pattern = 4'b1101; seg_pattern = SEG_R; end
                2'b10: begin anode_pattern = 4'b1011; seg_pattern = SEG_E; end
                2'b11: begin anode_pattern = 4'b0111; seg_pattern = SEG_M; end     // Leftmost
            endcase
        end else if (insertion_sort_active) begin
            // Display "InSt" for insertion sort
            case (digit_select)
                2'b00: begin anode_pattern = 4'b1110; seg_pattern = SEG_T; end         // Rightmost: "t"
                2'b01: begin anode_pattern = 4'b1101; seg_pattern = SEG_S; end         // "S"
                2'b10: begin anode_pattern = 4'b1011; seg_pattern = SEG_N_LOWER; end   // "n"
                2'b11: begin anode_pattern = 4'b0111; seg_pattern = SEG_I; end         // Leftmost: "I"
            endcase
        end else if (selection_sort_active) begin
            // Display "SELt" for selection sort
            case (digit_select)
                2'b00: begin anode_pattern = 4'b1110; seg_pattern = SEG_T_LOWER; end   // Rightmost: "t"
                2'b01: begin anode_pattern = 4'b1101; seg_pattern = SEG_L_UPPER; end   // "L"
                2'b10: begin anode_pattern = 4'b1011; seg_pattern = SEG_E; end         // "E"
                2'b11: begin anode_pattern = 4'b0111; seg_pattern = SEG_S; end         // Leftmost: "S"
            endcase
        end else if (bubble_sort_active) begin
            if (bubble_tutorial_mode) begin
                // Display "tutr" for tutorial mode
                case (digit_select)
                    2'b00: begin anode_pattern = 4'b1110; seg_pattern = SEG_R_LOWER; end   // Rightmost
                    2'b01: begin anode_pattern = 4'b1101; seg_pattern = SEG_T_LOWER; end
                    2'b10: begin anode_pattern = 4'b1011; seg_pattern = SEG_U_UPPER; end
                    2'b11: begin anode_pattern = 4'b0111; seg_pattern = SEG_T_LOWER; end   // Leftmost
                endcase
            end else begin
                // Display "bUbL" for demo mode
                case (digit_select)
                    2'b00: begin anode_pattern = 4'b1110; seg_pattern = SEG_L_UPPER; end   // Rightmost
                    2'b01: begin anode_pattern = 4'b1101; seg_pattern = SEG_B_LOWER; end
                    2'b10: begin anode_pattern = 4'b1011; seg_pattern = SEG_U_UPPER; end
                    2'b11: begin anode_pattern = 4'b0111; seg_pattern = SEG_B_LOWER; end   // Leftmost
                endcase
            end
        end else begin
            // All off when no algorithm active
            seg_pattern = 7'b1111111;
            anode_pattern = 4'b1111;
        end
    end

    // Segments are active-low, so invert the pattern
    assign seg = ~seg_pattern;
    assign an = anode_pattern;
    assign dp = 1'b1;  // Decimal point off (active-low)

endmodule
